name: 'NI Fiscal Council'
mail: admin@nifiscalcouncil.org
slogan: ''
page:
  403: ''
  404: ''
  front: /node
admin_compact_mode: false
weight_select_max: 100
langcode: en
default_langcode: en
_core:
  default_config_hash: IqFDJOUXgoqYSm39bzsb0BVMDSkw3b4-KD4YSUgMw7U
uuid: 78658025-1a4c-461b-8659-7cb4b769a5b1
frontpage_title: 'Welcome to Drupal site'
