_core:
  default_config_hash: IqFDJOUXgoqYSm39bzsb0BVMDSkw3b4-KD4YSUgMw7U
langcode: en
uuid: f29df4cb-3b8b-41fe-86c6-a8d76e4c2553
name: 'Northern Ireland Audit Office'
mail: info@niauditoffice.gov.uk
slogan: ''
page:
  403: ''
  404: ''
  front: /node
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
frontpage_title: 'Welcome to Northern Ireland Audit Office'
frontpage_show_title: 0
