# Each route describes how an incoming URL is going to be processed by Platform.sh.
"https://www.fictcommission.org/":
  type: upstream
  upstream: "unity:http"
  cache:
    enabled: false

"https://fictcommission.org.{default}/":
  type: redirect
  to: "https://www.fictcommission.org.{default}/"

"https://fictcommission.org/":
  type: redirect
  to: "https://www.fictcommission.org/"

#---------------------------------

"https://www.uregni.gov.uk/":
  type: upstream
  upstream: "unity:http"
  cache:
    enabled: false

"https://uregni.gov.uk.{default}/":
  type: redirect
  to: "https://www.uregni.gov.uk.{default}/"

"https://uregni.gov.uk/":
  type: redirect
  to: "https://www.uregni.gov.uk/"

#---------------------------------

"https://www.liofa.eu/":
  type: upstream
  upstream: "unity:http"
  cache:
    enabled: false

"https://liofa.eu.{default}/":
  type: redirect
  to: "https://www.liofa.eu.{default}/"

"https://liofa.eu/":
  type: redirect
  to: "https://www.liofa.eu/"

#---------------------------------

"https://www.odscni.org.uk/":
  type: upstream
  upstream: "unity:http"
  cache:
    enabled: false

"https://odscni.org.uk.{default}/":
  type: redirect
  to: "https://www.odscni.org.uk.{default}/"

"https://odscni.org.uk/":
  type: redirect
  to: "https://www.odscni.org.uk/"

#---------------------------------

"https://www.attorneygeneralni.gov.uk/":
  type: upstream
  upstream: "unity:http"
  cache:
    enabled: false

"https://attorneygeneralni.gov.uk.{default}/":
  type: redirect
  to: "https://www.attorneygeneralni.gov.uk.{default}/"

"https://attorneygeneralni.gov.uk/":
  type: redirect
  to: "https://www.attorneygeneralni.gov.uk/"

#---------------------------------

"https://www.employmenttribunalsni.co.uk/":
  type: upstream
  upstream: "unity:http"
  cache:
    enabled: false

"https://employmenttribunalsni.co.uk.{default}/":
  type: redirect
  to: "https://www.employmenttribunalsni.co.uk.{default}/"

"https://employmenttribunalsni.co.uk/":
  type: redirect
  to: "https://www.employmenttribunalsni.co.uk/"

#---------------------------------

#"https://www.hatecrimereviewni.org.uk/":
#  type: upstream
#  upstream: "unity:http"
#  cache:
#    enabled: false
#
#"http://hatecrimereviewni.org.uk.{default}/":
#  type: redirect
#  to: "http://www.hatecrimereviewni.org.uk.{default}/"
#
#"http://hatecrimereviewni.org.uk/":
#  type: redirect
#  to: "http://www.hatecrimereviewni.org.uk/"

#---------------------------------

"https://www.fiscalcommissionni.org/":
  type: upstream
  upstream: "unity:http"
  cache:
    enabled: false

"https://fiscalcommissionni.org/":
  type: redirect
  to: "https://www.fiscalcommissionni.org/"

#---------------------------------

"https://www.nifiscalcouncil.org/":
  type: upstream
  upstream: "unity:http"
  cache:
    enabled: false

"https://nifiscalcouncil.org.{default}/":
  type: redirect
  to: "https://www.nifiscalcouncil.org.{default}/"


#---------------------------------
# Catch all.
"https://www.{all}/":
  type: upstream
  upstream: "unity:http"
  cache:
    enabled: false

"https://{all}/":
  type: redirect
  to: "https://www.{all}/"
