menus:
  -
    menu_name: main
    title: Home
    parent: null
    uri: 'internal:/'
    link_title: null
    description: null
    enabled: '1'
    expanded: '0'
    weight: '-50'
    langcode: und
    uuid: c3f4422e-1a47-4c51-8100-9f800e1f49c4
  -
    menu_name: main
    title: 'About NIAO'
    parent: null
    uri: 'entity:node/2'
    link_title: null
    description: null
    enabled: '1'
    expanded: '0'
    weight: '-49'
    langcode: und
    uuid: 8e7e1dd5-63e3-4243-9548-fe945de1a40e
  -
    menu_name: main
    title: Publications
    parent: null
    uri: 'internal:/publications'
    link_title: null
    description: null
    enabled: '1'
    expanded: '0'
    weight: '-47'
    langcode: und
    uuid: 9fd4abfc-8d3f-4f3d-bf6b-44109a0f195b
  -
    menu_name: main
    title: Careers
    parent: null
    uri: 'entity:node/4'
    link_title: null
    description: null
    enabled: '1'
    expanded: '0'
    weight: '-46'
    langcode: und
    uuid: bf6d2be1-4d9a-4972-b30e-7dc9462f521a
  -
    menu_name: main
    title: 'Fraud and Raising Concerns'
    parent: null
    uri: 'entity:node/5'
    link_title: null
    description: null
    enabled: '1'
    expanded: '0'
    weight: '-45'
    langcode: und
    uuid: 215203a4-1da6-47b3-af2e-7af665978389
  -
    menu_name: main
    title: 'Role of Comptroller & Auditor General'
    parent: 'menu_link_content:8e7e1dd5-63e3-4243-9548-fe945de1a40e'
    uri: 'entity:node/10'
    link_title: null
    description: null
    enabled: '1'
    expanded: '0'
    weight: '-50'
    langcode: und
    uuid: d40da991-008d-44be-ba9d-b89e6275a341
  -
    menu_name: main
    title: 'Profile of C&AG'
    parent: 'menu_link_content:8e7e1dd5-63e3-4243-9548-fe945de1a40e'
    uri: 'entity:node/11'
    link_title: null
    description: null
    enabled: '1'
    expanded: '0'
    weight: '-49'
    langcode: und
    uuid: 5bc2bbb7-312a-405e-9ccb-84eb8df3e38e
  -
    menu_name: main
    title: 'Vision Purpose Values'
    parent: 'menu_link_content:8e7e1dd5-63e3-4243-9548-fe945de1a40e'
    uri: 'entity:node/15'
    link_title: null
    description: null
    enabled: '1'
    expanded: '0'
    weight: '-48'
    langcode: und
    uuid: b7a5f535-c44f-4cb5-808f-d59bc02a5bbb
  -
    menu_name: main
    title: 'Senior Management'
    parent: 'menu_link_content:8e7e1dd5-63e3-4243-9548-fe945de1a40e'
    uri: 'entity:node/16'
    link_title: null
    description: null
    enabled: '1'
    expanded: '0'
    weight: '-47'
    langcode: und
    uuid: 9a47f5f3-a563-42d6-81b8-ec4222500c66
  -
    menu_name: main
    title: 'Governance of NIAO'
    parent: 'menu_link_content:8e7e1dd5-63e3-4243-9548-fe945de1a40e'
    uri: 'entity:node/21'
    link_title: null
    description: null
    enabled: '1'
    expanded: '0'
    weight: '-45'
    langcode: und
    uuid: ea1e64f9-269c-4ce0-8cff-8ec84495b9d7
  -
    menu_name: main
    title: 'Advisory Board'
    parent: 'menu_link_content:ea1e64f9-269c-4ce0-8cff-8ec84495b9d7'
    uri: 'entity:node/22'
    link_title: null
    description: null
    enabled: '1'
    expanded: '0'
    weight: '-50'
    langcode: und
    uuid: 292017e7-3928-4563-a04f-7fb72b60ebcf
  -
    menu_name: main
    title: 'Senior Management Team'
    parent: 'menu_link_content:ea1e64f9-269c-4ce0-8cff-8ec84495b9d7'
    uri: 'entity:node/23'
    link_title: null
    description: null
    enabled: '1'
    expanded: '0'
    weight: '-47'
    langcode: und
    uuid: a7f257c9-1c6f-4c8d-a7df-08193eee7e8c
  -
    menu_name: main
    title: 'Audit and Risk Assurance Committee'
    parent: 'menu_link_content:ea1e64f9-269c-4ce0-8cff-8ec84495b9d7'
    uri: 'entity:node/24'
    link_title: null
    description: null
    enabled: '1'
    expanded: '0'
    weight: '-49'
    langcode: und
    uuid: 4265e876-5245-4755-89c0-5b033368f899
  -
    menu_name: main
    title: 'Central Government Financial Audit'
    parent: 'menu_link_content:8e7e1dd5-63e3-4243-9548-fe945de1a40e'
    uri: 'entity:node/30'
    link_title: null
    description: null
    enabled: '1'
    expanded: '0'
    weight: '10'
    langcode: und
    uuid: d3e921c4-5f29-4de5-961f-4deafc679ad2
  -
    menu_name: main
    title: 'Local Government Audit'
    parent: 'menu_link_content:8e7e1dd5-63e3-4243-9548-fe945de1a40e'
    uri: 'entity:node/31'
    link_title: null
    description: null
    enabled: '1'
    expanded: '0'
    weight: '12'
    langcode: und
    uuid: edd2b61c-b5b0-4f6f-ad59-1e8a28aeb945
  -
    menu_name: main
    title: 'Value For Money Audit'
    parent: 'menu_link_content:8e7e1dd5-63e3-4243-9548-fe945de1a40e'
    uri: 'entity:node/32'
    link_title: null
    description: null
    enabled: '1'
    expanded: '0'
    weight: '13'
    langcode: und
    uuid: 7a8cb015-9eed-4dd2-b027-e832824bd545
  -
    menu_name: main
    title: 'Value For Money Cycle'
    parent: 'menu_link_content:7a8cb015-9eed-4dd2-b027-e832824bd545'
    uri: 'entity:node/33'
    link_title: null
    description: null
    enabled: '1'
    expanded: '0'
    weight: '-49'
    langcode: und
    uuid: 9f560fb0-82c4-487f-b8c3-712e000ddbd2
  -
    menu_name: main
    title: 'VFM Standards'
    parent: 'menu_link_content:7a8cb015-9eed-4dd2-b027-e832824bd545'
    uri: 'entity:node/34'
    link_title: null
    description: null
    enabled: '1'
    expanded: '0'
    weight: '-48'
    langcode: und
    uuid: ec855efb-ea35-4330-9f63-c7f61218d5fe
  -
    menu_name: main
    title: 'Public Accounts Committee'
    parent: 'menu_link_content:7a8cb015-9eed-4dd2-b027-e832824bd545'
    uri: 'entity:node/35'
    link_title: null
    description: null
    enabled: '1'
    expanded: '0'
    weight: '-50'
    langcode: und
    uuid: 7d9b4157-3425-4dee-8c3a-f20316225fe0
  -
    menu_name: main
    title: 'Freedom of Information'
    parent: 'menu_link_content:57c33a05-b9a5-44d8-8444-12bd7b791e5c'
    uri: 'entity:node/39'
    link_title: null
    description: null
    enabled: '1'
    expanded: '0'
    weight: '-50'
    langcode: und
    uuid: 3d88987c-7836-4a9b-9173-89dd7c07a5e0
  -
    menu_name: main
    title: 'Complaints Page'
    parent: 'menu_link_content:57c33a05-b9a5-44d8-8444-12bd7b791e5c'
    uri: 'entity:node/40'
    link_title: null
    description: null
    enabled: '1'
    expanded: '0'
    weight: '-46'
    langcode: und
    uuid: f667af21-3191-4882-bf24-7547d4850ce3
  -
    menu_name: main
    title: 'Publication Scheme'
    parent: 'menu_link_content:8471fdad-5d64-44a6-9e80-9836ade2e7fc'
    uri: 'entity:node/41'
    link_title: null
    description: null
    enabled: '0'
    expanded: '0'
    weight: '-19'
    langcode: und
    uuid: 5af9d16d-9c4b-4486-931f-d21b476d6ddb
  -
    menu_name: main
    title: 'Who we are and what we do'
    parent: 'menu_link_content:5af9d16d-9c4b-4486-931f-d21b476d6ddb'
    uri: 'entity:node/42'
    link_title: null
    description: null
    enabled: '1'
    expanded: '0'
    weight: '-24'
    langcode: und
    uuid: ade2197e-ab64-4cf3-8824-22dea5174d5a
  -
    menu_name: main
    title: 'What we spend and how we spend it'
    parent: 'menu_link_content:5af9d16d-9c4b-4486-931f-d21b476d6ddb'
    uri: 'entity:node/43'
    link_title: null
    description: null
    enabled: '0'
    expanded: '0'
    weight: '-15'
    langcode: und
    uuid: a9524773-c2d5-45c7-92e2-78f34439026c
  -
    menu_name: main
    title: 'What are our priorities and how are we doing'
    parent: 'menu_link_content:5af9d16d-9c4b-4486-931f-d21b476d6ddb'
    uri: 'entity:node/44'
    link_title: null
    description: null
    enabled: '0'
    expanded: '0'
    weight: '-6'
    langcode: und
    uuid: 4472d1dc-0428-4115-91a8-104f07cb669e
  -
    menu_name: main
    title: 'How we make decisions'
    parent: 'menu_link_content:5af9d16d-9c4b-4486-931f-d21b476d6ddb'
    uri: 'entity:node/45'
    link_title: null
    description: null
    enabled: '0'
    expanded: '0'
    weight: '-3'
    langcode: und
    uuid: a91c2e5a-7dd3-4401-9793-2b177df9328c
  -
    menu_name: main
    title: 'Our Policies and Procedures'
    parent: 'menu_link_content:62cfd77a-7144-42d4-add2-af4669536575'
    uri: 'entity:node/46'
    link_title: null
    description: null
    enabled: '1'
    expanded: '0'
    weight: '-46'
    langcode: und
    uuid: 051bcc7b-c169-4a2b-925f-e15f205be3be
  -
    menu_name: main
    title: 'Lists and Registers'
    parent: 'menu_link_content:62cfd77a-7144-42d4-add2-af4669536575'
    uri: 'entity:node/47'
    link_title: null
    description: null
    enabled: '1'
    expanded: '0'
    weight: '-47'
    langcode: und
    uuid: 6d7b9e17-3ac8-443b-9690-e22f73d8b90b
  -
    menu_name: main
    title: 'Our work and its outcomes'
    parent: 'menu_link_content:5af9d16d-9c4b-4486-931f-d21b476d6ddb'
    uri: 'entity:node/48'
    link_title: null
    description: null
    enabled: '0'
    expanded: '0'
    weight: '4'
    langcode: und
    uuid: 1c3c7c24-a007-433b-961c-d76b1f07e390
  -
    menu_name: main
    title: 'Non Executive Members'
    parent: 'menu_link_content:ea1e64f9-269c-4ce0-8cff-8ec84495b9d7'
    uri: 'entity:node/50'
    link_title: null
    description: null
    enabled: '1'
    expanded: '0'
    weight: '-48'
    langcode: und
    uuid: 98062ffc-c24e-4c12-bb82-33825c2e16e1
  -
    menu_name: main
    title: 'Corporate Documents'
    parent: 'menu_link_content:8e7e1dd5-63e3-4243-9548-fe945de1a40e'
    uri: 'entity:node/95'
    link_title: null
    description: null
    enabled: '1'
    expanded: '0'
    weight: '-48'
    langcode: und
    uuid: 62cfd77a-7144-42d4-add2-af4669536575
  -
    menu_name: main
    title: 'Corporate Plan'
    parent: 'menu_link_content:62cfd77a-7144-42d4-add2-af4669536575'
    uri: 'entity:node/99'
    link_title: null
    description: null
    enabled: '1'
    expanded: '0'
    weight: '-44'
    langcode: und
    uuid: 62d35da7-b486-4b73-b746-c078dd1bc358
  -
    menu_name: main
    title: 'Annual Report and Accounts'
    parent: 'menu_link_content:62cfd77a-7144-42d4-add2-af4669536575'
    uri: 'entity:node/100'
    link_title: null
    description: null
    enabled: '1'
    expanded: '0'
    weight: '-50'
    langcode: und
    uuid: 31726eab-44bc-41ae-b00c-d42071246c34
  -
    menu_name: main
    title: Equality
    parent: 'menu_link_content:62cfd77a-7144-42d4-add2-af4669536575'
    uri: 'entity:node/101'
    link_title: null
    description: null
    enabled: '1'
    expanded: '0'
    weight: '-48'
    langcode: und
    uuid: 6452059a-914b-4b46-9234-37ac22c6ea66
  -
    menu_name: main
    title: 'Consultation Documents'
    parent: 'menu_link_content:62cfd77a-7144-42d4-add2-af4669536575'
    uri: 'entity:node/103'
    link_title: null
    description: null
    enabled: '1'
    expanded: '0'
    weight: '-49'
    langcode: und
    uuid: 1e9a943f-8422-4ce5-aa96-e5a70f69a3a3
  -
    menu_name: main
    title: Other
    parent: 'menu_link_content:62cfd77a-7144-42d4-add2-af4669536575'
    uri: 'entity:node/104'
    link_title: null
    description: null
    enabled: '1'
    expanded: '0'
    weight: '-43'
    langcode: und
    uuid: 8471fdad-5d64-44a6-9e80-9836ade2e7fc
  -
    menu_name: main
    title: News
    parent: 'menu_link_content:57c33a05-b9a5-44d8-8444-12bd7b791e5c'
    uri: 'internal:/news'
    link_title: null
    description: null
    enabled: '0'
    expanded: '0'
    weight: '-48'
    langcode: und
    uuid: a7261d3e-857a-4906-bafd-81dedbc5384a
  -
    menu_name: main
    title: 'Public Reporting Programme'
    parent: 'menu_link_content:62cfd77a-7144-42d4-add2-af4669536575'
    uri: 'entity:node/403'
    link_title: ''
    description: 'Public Reporting Programme'
    enabled: '1'
    expanded: '0'
    weight: '-45'
    langcode: und
    uuid: 9fa4c469-64d3-4965-865e-2954c3ce45c9
  -
    menu_name: main
    title: 'Remuneration Committee'
    parent: 'menu_link_content:ea1e64f9-269c-4ce0-8cff-8ec84495b9d7'
    uri: 'entity:node/494'
    link_title: ''
    description: null
    enabled: '1'
    expanded: '0'
    weight: '-46'
    langcode: und
    uuid: 5edffb72-7c1a-4d61-80bf-d4a711d56c28
  -
    menu_name: main
    title: 'Press Office'
    parent: 'menu_link_content:57c33a05-b9a5-44d8-8444-12bd7b791e5c'
    uri: 'entity:node/503'
    link_title: null
    description: 'Contact details for press office'
    enabled: '1'
    expanded: '0'
    weight: '-47'
    langcode: und
    uuid: 0e93fbfd-dd5c-47fd-90c6-76c66460dc22
  -
    menu_name: main
    title: 'Our People'
    parent: 'menu_link_content:bf6d2be1-4d9a-4972-b30e-7dc9462f521a'
    uri: 'entity:node/523'
    link_title: ''
    description: null
    enabled: '1'
    expanded: '0'
    weight: '-49'
    langcode: und
    uuid: 63130901-cee9-4cbb-87ed-5eaad32e93ff
  -
    menu_name: main
    title: 'Benefits of working with the NIAO'
    parent: 'menu_link_content:bf6d2be1-4d9a-4972-b30e-7dc9462f521a'
    uri: 'entity:node/524'
    link_title: ''
    description: null
    enabled: '1'
    expanded: '0'
    weight: '-48'
    langcode: und
    uuid: 5c290dc5-ec27-4ddd-a8ae-d00abec70ced
  -
    menu_name: main
    title: 'Trainee Accountant Scheme'
    parent: 'menu_link_content:bf6d2be1-4d9a-4972-b30e-7dc9462f521a'
    uri: 'entity:node/443'
    link_title: ''
    description: null
    enabled: '1'
    expanded: '0'
    weight: '-47'
    langcode: und
    uuid: f500da9d-f9d2-48ad-91b5-180c39f78853
  -
    menu_name: main
    title: 'Opportunities to work with us'
    parent: 'menu_link_content:bf6d2be1-4d9a-4972-b30e-7dc9462f521a'
    uri: 'entity:node/525'
    link_title: ''
    description: null
    enabled: '1'
    expanded: '0'
    weight: '-46'
    langcode: und
    uuid: 65e8c323-e68b-428c-87dd-538b3f65d8cc
  -
    menu_name: main
    title: 'Frequently Asked Questions'
    parent: 'menu_link_content:57c33a05-b9a5-44d8-8444-12bd7b791e5c'
    uri: 'entity:node/560'
    link_title: ''
    description: null
    enabled: '1'
    expanded: '0'
    weight: '-49'
    langcode: en
    uuid: 4af43311-2e23-4326-a6cf-3505805ebcad
  -
    menu_name: main
    title: 'Contact us'
    parent: null
    uri: 'entity:node/559'
    link_title: ''
    description: null
    enabled: '1'
    expanded: '0'
    weight: '0'
    langcode: en
    uuid: 57c33a05-b9a5-44d8-8444-12bd7b791e5c
  -
    menu_name: footer-menu
    title: 'Â© Northern Ireland Audit Office'
    parent: null
    uri: 'entity:node/7'
    link_title: ''
    description: null
    enabled: '1'
    expanded: '0'
    weight: '-50'
    langcode: en
    uuid: 53048506-7c5d-4fa3-b317-9badad8de7c7
  -
    menu_name: footer-menu
    title: 'Terms and Conditions'
    parent: null
    uri: 'entity:node/8'
    link_title: ''
    description: null
    enabled: '1'
    expanded: '0'
    weight: '-49'
    langcode: en
    uuid: 89e7992d-934f-4f81-acf5-74bbd8184829
  -
    menu_name: footer-menu
    title: 'Complaints procedure'
    parent: null
    uri: 'entity:node/9'
    link_title: ''
    description: null
    enabled: '1'
    expanded: '0'
    weight: '-48'
    langcode: en
    uuid: f435428b-417a-4a7c-b8b5-e8cff87d1299
  -
    menu_name: footer-menu
    title: Accessibility
    parent: null
    uri: 'entity:node/388'
    link_title: ''
    description: null
    enabled: '1'
    expanded: '0'
    weight: '-47'
    langcode: en
    uuid: dd227511-0719-457d-a7ab-901ed73cae28
  -
    menu_name: footer-menu
    title: 'Privacy notice'
    parent: null
    uri: 'entity:node/357'
    link_title: ''
    description: null
    enabled: '1'
    expanded: '0'
    weight: '-46'
    langcode: en
    uuid: 14076b44-ce2e-43ed-8d2b-5b9679decf38
blocks:
  -
    info: 'What we do'
    langcode: en
    uuid: 8710f557-2dab-40d0-a4af-a0a19ba08a9b
    bundle: basic_block
    revision_id: null
    rev_id_current: null
    fields:
      body:
        -
          value: "<h3>Financial Audit</h3>\r\n\r\n<ul>\r\n\t<li><a href=\"/node/30\">Central Government Audits</a></li>\r\n\t<li><a data-entity-substitution=\"canonical\" data-entity-type=\"node\" data-entity-uuid=\"78ed7a8b-2e96-4c00-ab32-d25f0c5f8719\" href=\"/node/31\">Local Government Audits</a></li>\r\n</ul>\r\n\r\n<h3>Value for money audit</h3>\r\n\r\n<p><a href=\"/node/32\"><span>Read more</span></a></p>\r\n"
          summary: ''
          format: basic_html
  -
    info: 'Footer Contact information'
    langcode: en
    uuid: 7853c171-cf18-4d0d-9133-3c2f7cc34147
    bundle: basic_block
    revision_id: null
    rev_id_current: null
    fields:
      body:
        -
          value: "<address>Northern Ireland Audit Office<br />\r\n1 Bradford Court, Upper Galwally<br />\r\nBelfast<br />\r\nBT8 6RB<br />\r\nT: (028) 9025 1000<br />\r\nF: (028) 9025 1106 or (028) 9025 1051<br />\r\nE:&nbsp;<a href=\"mailto:info@niauditoffice.gov.uk\">info@niauditoffice.gov.uk</a></address>\r\n"
          summary: ''
          format: basic_html
  -
    info: 'Footer Useful links'
    langcode: en
    uuid: 735e1f34-f69d-44f2-97da-b4a43be6df5f
    bundle: basic_block
    revision_id: null
    rev_id_current: null
    fields:
      body:
        -
          value: "<ul>\r\n\t<li><a href=\"http://www.nao.org.uk/\">National Audit Office</a></li>\r\n\t<li><a href=\"http://www.audit-scotland.gov.uk/\">Audit Scotland</a></li>\r\n\t<li><a href=\"http://www.wao.gov.uk/\">Audit Wales</a></li>\r\n\t<li><a href=\"http://audgen.gov.ie/\">Office of the C&amp;AG Dublin</a></li>\r\n</ul>\r\n"
          summary: null
          format: basic_html
  -
    info: 'Footer subscription'
    langcode: en
    uuid: 8dc9a7f3-2fdb-4848-bf4a-ca89e2fc142c
    bundle: basic_block
    revision_id: null
    rev_id_current: null
    fields:
      body:
        -
          value: "<h2>Subscribe to our news email alert service</h2>\r\n"
          summary: ''
          format: basic_html
  -
    info: 'Social links'
    langcode: en
    uuid: 6fc864c3-256a-4811-9bba-1cd4e3ec22be
    bundle: basic_block
    revision_id: null
    rev_id_current: null
    fields:
      body: {  }
